#!/bin/bash
set -euo pipefail

TMP_FILE=$(mktemp "/${TMPDIR:-tmp}/vim-everywhere-XXXXXX")

umask 0066  # Create files only with rw for user.
vim "$TMP_FILE"

if [ ! -f "$TMP_FILE" ]; then
    exit 0
fi

xclip -selection clipboard "$TMP_FILE"
rm "$TMP_FILE"

# Don't ask me why, but clipboard doesn't get populated
# without a sleep.
sleep 0.01

